INSERT INTO supply_kinds (id, name) VALUES (1, 'Магазин канцтоваров');
INSERT INTO supply_kinds (id, name) VALUES (2, 'Спортивный магазин');
INSERT INTO supply_kinds (id, name) VALUES (3, 'Туристический магазин');
INSERT INTO supply_kinds (id, name) VALUES (4, 'Магазин фототоваров');
INSERT INTO supply_kinds (id, name) VALUES (5, 'Книжный магазин');
INSERT INTO supply_kinds (id, name) VALUES (6, 'Супермаркет');
INSERT INTO supply_kinds (id, name) VALUES (7, 'Продуктовый магазин');
INSERT INTO supply_kinds (id, name) VALUES (8, 'Хозяйственный магазин');
INSERT INTO supply_kinds (id, name) VALUES (9, 'Банк');
INSERT INTO supply_kinds (id, name) VALUES (10, 'Шахматный клуб');
INSERT INTO supply_kinds (id, name) VALUES (11, 'Фонд');
INSERT INTO supply_kinds (id, name) VALUES (12, 'Риэлтерское агентство');
INSERT INTO supply_kinds (id, name) VALUES (13, 'Высшее учебное заведение');
INSERT INTO supply_kinds (id, name) VALUES (14, 'Общеобразовательная школа');
INSERT INTO supply_kinds (id, name) VALUES (15, 'Библиотека');
INSERT INTO supply_kinds (id, name) VALUES (16, 'Сфера услуг');
INSERT INTO supply_kinds (id, name) VALUES (17, 'Кафе');
INSERT INTO supply_kinds (id, name) VALUES (18, 'Ресторан');
INSERT INTO supply_kinds (id, name) VALUES (19, 'Туристическое агентство');
INSERT INTO supply_kinds (id, name) VALUES (20, 'Ночной клуб');
INSERT INTO supply_kinds (id, name) VALUES (21, 'Спортивный комплекс');
INSERT INTO supply_kinds (id, name) VALUES (22, 'Санаторий');
INSERT INTO supply_kinds (id, name) VALUES (23, 'Такси');
INSERT INTO supply_kinds (id, name) VALUES (24, 'Театр');
INSERT INTO supply_kinds (id, name) VALUES (25, 'Гаражно-строительный кооператив');
INSERT INTO supply_kinds (id, name) VALUES (26, 'Аптека');
INSERT INTO supply_kinds (id, name) VALUES (27, 'Сеть организаций');
INSERT INTO supply_kinds (id, name) VALUES (28, 'Средство массовой информации');
INSERT INTO supply_kinds (id, name) VALUES (29, 'Справочная');
INSERT INTO supply_kinds (id, name) VALUES (30, 'Орган власти');
INSERT INTO supply_kinds (id, name) VALUES (98, 'Служба');
INSERT INTO supply_kinds (id, name) VALUES (99, 'Другое');
