package SavingsServer;


/**
* SavingsServer/Hello.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../server/SavingsServer.idl
* 20 Ноябрь 2005 г. 1:24:59 MSK
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
