package SavingsServer;


/**
* SavingsServer/HelloOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../server/SavingsServer.idl
* 20 Ноябрь 2005 г. 13:57:04 MSK
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
