<%--
--%><%@ page language="java" %><%--
--%><%@ page contentType="text/html; charset=UTF-8" %><%--
--%><%@ taglib prefix="jstl" uri="jstl_core" %><%--
--%><?xml version="1.0" encoding="UTF-8"?>
<%--
--%><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%--
--%><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru"><%--
 --%><head><%--
  --%><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><%--
  --%><meta http-equiv="Content-Style-Type" content="text/css"/><%--
  --%><meta http-equiv="Content-Script-Type" content="text/javascript"/><%--
  --%><link rel="stylesheet" href="<jstl:out value="${pageContext.request.contextPath}"/>/style.css" type="text/css"/><%--
  --%><meta http-equiv="Refresh" content="0; url=<jstl:out value="${pageContext.request.contextPath}"/>/controller"/><%--
  --%><title>База данных &quot;Контакты&quot;</title><%--
 --%></head><%--
 --%><body><%--
  --%><div align="center"><%--
   --%><table style="width: 50%"><%--
    --%><colgroup span="1"/><%--
    --%><tbody><%--
     --%><tr><%--
      --%><td><%--
       --%>Если Вы видите эту страничку продолжительное время, <%--
       --%>больше 20 секунд, значит Ваш браузер не обладает достаточной <%--
       --%>функциональностью. <%--
       --%>Тем не менее, Вы можете <%--
        --%><a href="<jstl:out value="${pageContext.request.contextPath}"/>/controller">начать работу с системой</a>.<%--
      --%></td><%--
     --%></tr><%--
    --%></tbody><%--
  --%></table><%--
 --%></body><%--
--%></html>