<%--
--%><%@ page contentType="text/html; charset=UTF-8" %><%--
--%><%@ taglib prefix="logic" uri="struts_logic" %><%--
--%><%@ taglib prefix="jstl" uri="jstl_core" %><%--
--%><%@ taglib prefix="fmt" uri="jstl_fmt" %><%--
--%><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<%--
--%><!-- jsps/person/search.jsp { --><%--
--%><html><%--
 --%><head><%--
  --%><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><%--
  --%><meta http-equiv="Content-Style-Type" content="text/css"><%--
  --%><meta http-equiv="Content-Script-Type" content="text/javascript"><%--
  --%><title>Поиск личности - База данных &quot;Контакты&quot;</title><%--
  --%><link rel="stylesheet" type="text/css" media="all" href="<jstl:out value="${pageContext.request.contextPath}"/>/calendar/calendar.css" title="default" /><%--
  --%><script type="text/javascript" src="<jstl:out value="${pageContext.request.contextPath}"/>/calendar/calendar.js"></script><%--
  --%><script type="text/javascript" src="<jstl:out value="${pageContext.request.contextPath}"/>/calendar/lang/calendar-ru.js" charset="UTF-8"></script><%--
  --%><script type="text/javascript" src="<jstl:out value="${pageContext.request.contextPath}"/>/calendar/calendar-setup.js"></script><%--
  --%><link rel="stylesheet" href="<jstl:out value="${pageContext.request.contextPath}"/>/style.css" type="text/css"><%--
  --%><link rel="SHORTCUT ICON" href="<jstl:out value="${pageContext.request.contextPath}"/>/shortcut.ico"/><%--
  --%><script type="text/javascript" src="<jstl:out value="${pageContext.request.contextPath}"/>/js/utils.js"></script><%--
  --%><script type="text/javascript"> // <![CDATA[<%--
   --%>
   <%--
   --%>function clearSearchForm(form) {<%--
       --%>form.address.value = "";<%--
       --%>form.birthyear.value="";<%--
       --%>form.email.value = "";<%--
       --%>form.firstName.value = "";<%--
       --%>form.gender.selectedIndex = 0;<%--
       --%><jstl:if test="${not empty Sergey}"><%--
       --%> form.groupMode.selectedIndex = 0;<%--
       --%> form.note.value = "";<%--
       --%></jstl:if><%--
       --%>form.icq.value = "";<%--
       --%>form.lastName.value = "";<%--
       --%>form.middleName.value = "";<%--
       --%>form.monthOfBirthday.selectedIndex = 0;<%--
       --%>form.phone.value = "";<%--
   --%>}<%--
   --%>
   <%--
   --%>function toBirthDate() {<%--
       --%>document.getElementById("searchForm").birthdate.value = "01.01." + document.getElementById("searchForm").birthyear.value;<%--
   --%>}<%--
   --%>
   <%--
   --%>function fromBirthDate() {<%--
       --%>document.getElementById("searchForm").birthyear.value = document.getElementById("searchForm").birthdate.value.substring(6, 10);<%--
   --%>}<%--
   --%>
   <%--
   --%>function onLoad() {<%--
       --%>document.getElementById("birthyearId").readOnly = true;<%--
       --%>document.getElementById("birthyearImg").tabIndex = document.getElementById("birthyearId").tabIndex;<%--
       --%>document.getElementById("birthyearId").tabIndex = -1;<%--
       --%>document.getElementById("lastNameId").focus();<%--
   --%>}<%--
 --%>// ]]></script><%--
 --%></head><%--
 --%><body onload="onLoad()"><%--
  --%><jsp:include page="/include/menu.jsp" flush="true"/><%--
  --%><p style="text-align: left">Поиск личности</p><%--
  --%><jstl:if test="${not empty personSearchParameters}"><%--
   --%><div align="right"><%--
    --%><jstl:if test="${not empty persons && not empty Sergey}"><%--
     --%><a href="<jstl:out value="${pageContext.request.contextPath}"/>/controller?action=report.pagePersons" target="report">Отчет</a><%--
    --%></jstl:if><%--
    --%><jstl:if test="${empty persons && (not empty Sergey or not empty Editor)}"><%--
     --%><a href="<jstl:out value="${pageContext.request.contextPath}"/>/controller?action=person.view" accessKey="д">Создать</a><%--
    --%></jstl:if><%--
   --%></div><%--
  --%></jstl:if><%--
  --%><jstl:if test="${not empty persons}"><%--
   --%><jsp:include page="/include/person/search_results.jsp" flush="true"/><%--
  --%></jstl:if><%--
  --%><jstl:if test="${empty persons and not empty personSearchParameters}"><%--
   --%><jsp:include page="/include/not_found.jsp" flush="true"/><%--
  --%></jstl:if><%--
  --%><form id="searchForm" method="get" action="<jstl:out value="${pageContext.request.contextPath}"/>/controller"><%--
   --%><input type="hidden" name="action" value="person.search"><%--
   --%><table style="width: 100%" class="form" frame="border"><%--
    --%><colgroup span="6"/><%--
    --%><thead><%--
     --%><tr><%--
      --%><th colspan="6">Параметры поиска</th><%--
     --%></tr><%--
    --%></thead><%--
    --%><tbody><%--
     --%><tr><%--
      --%><td style="text-align: right"><label for="lastNameId">Фамилия</label></td><%--
      --%><td><%--
       --%><input id="lastNameId" type="text" class="elem" name="lastName" size="20" value="<jstl:out value="${personSearchParameters.lastName}"/>" tabindex="11"><%--
      --%></td><%--
      --%><td style="text-align: right"><label for="emailId">Электронная почта</label></td><%--
      --%><td><%--
       --%><input id="emailId" name="email" class="elem" size="20" value="<jstl:out value="${personSearchParameters.email}"/>" tabindex="15"><%--
      --%></td><%--
      --%><td style="text-align: right"><label for="genderId">Пол</label></td><%--
      --%><td><%--
       --%><select id="genderId" name="gender" class="elem" tabindex="19"><%--
        --%><option value="">Не имеет значения</option><%--
        --%><logic:iterate name="inquire_genders_1" id="gender"><%--
         --%><option value="<jstl:out value="${gender.id}"/>"<jstl:if test="${personSearchParameters.gender == gender.id}"> selected</jstl:if>><jstl:out value="${gender.name}"/></option><%--
        --%></logic:iterate><%--
       --%></select><%--
      --%></td><%--
     --%></tr><%--
     --%><tr><%--
      --%><td style="text-align: right"><label for="firstNameId">Имя</label></td><%--
      --%><td><%--
       --%><input id="firstNameId" type="text" class="elem" name="firstName" size="20" value="<jstl:out value="${personSearchParameters.firstName}"/>" tabindex="12"><%--
      --%></td><%--
      --%><td style="text-align: right"><label for="addressId">Адрес</label></td><%--
      --%><td><%--
       --%><input id="addressId" name="address" class="elem" size="20" value="<jstl:out value="${personSearchParameters.address}"/>" tabindex="16"><%--
      --%></td><%--
      --%><td style="text-align: right"><label for="monthOfBirthdayId">Месяц рождения</label></td><%--
      --%><td><%--
       --%><select id="monthOfBirthdayId" name="monthOfBirthday" class="elem" tabindex="20"><%--
        --%><option value="-1">------- ------------ -------</option><%--
        --%><logic:iterate name="inquire_months_1" id="month" type="su.sergey.contacts.inquiry.valueobjects.InquiryObject"><%--
         --%><option value="<jstl:out value="${month.id}"/>"<jstl:if test="${personSearchParameters.monthOfBirthday == month.id}"> selected</jstl:if>><jstl:out value="${month.name}"/></option><%--
        --%></logic:iterate><%--
       --%></select><%--
      --%></td><%--
     --%></tr><%--
     --%><tr><%--
      --%><td style="text-align: right"><label for="middleNameId">Отчество</label></td><%--
      --%><td><%--
       --%><input id="middleNameId" name="middleName" type="text" class="elem" size="20" value="<jstl:out value="${personSearchParameters.middleName}"/>" tabindex="13"><%--
      --%></td><%--
      --%><td style="text-align: right"><label for="icqId">ICQ</label></td><%--
      --%><td><%--
       --%><input id="icqId" name="icq" class="elem" size="20" value="<jstl:out value="${personSearchParameters.icq}"/>" tabindex="17"><%--
      --%></td><%--
      --%><td style="text-align: right"><label for="birthyearId">Год рождения</label></td><%--
      --%><td><%--
       --%><input id="birthyearId" name="birthyear" size="4" maxLength="4" class="only_year" onchange="toBirthDate()" value="<fmt:formatDate pattern="yyyy" value="${personSearchParameters.yearOfBirthday}"/>" tabindex="21"><%--
       --%><a href="javascript:void(0)" id="birthyearImg"><img src="<jstl:out value="${pageContext.request.contextPath}"/>/images/ico_insert.gif" width="14" height="16" border="0" alt="^" title="Календарь"></a><%--
       --%><script> // <![CDATA[<%--
        --%>
        <%--
        --%>Calendar.setup({<%--
            --%>inputField: "birthyearId",<%--
            --%>ifFormat: "%Y",<%--
            --%>button: "birthyearImg",<%--
            --%>firstDay: 1,<%--
            --%>weekNumbers: false,<%--
            --%>showOthers: true,<%--
            --%>singleClick: true<%--
            --%>});<%--
       --%>// ]]></script><%--
       --%><input type="hidden" name="birthdate"><%--
      --%></td><%--
     --%></tr><%--
     --%><tr><%--     
      --%><td style="text-align: right"><label for="phoneId">Телефон</label></td><%--
      --%><td><%--
       --%><input id="phoneId" name="phone" type="text" class="elem" size="20" value="<jstl:out value="${personSearchParameters.phone}"/>" tabindex="14"><%--
      --%></td><%--
      --%><td style="text-align: right"><%--
       --%><jstl:if test="${not empty Sergey}"><%--
        --%><label for="noteId">Примечание</label><%--
       --%></jstl:if><%--
      --%></td><%--
      --%><td><%--
       --%><jstl:if test="${not empty Sergey}"><%--
        --%><input id="noteId" name="note" type="text" class="elem" size="20" value="<jstl:out value="${personSearchParameters.note}"/>" tabindex="18"><%--
       --%></jstl:if><%--
      --%></td><%--
      --%><td style="text-align: right"><%--
       --%><jstl:if test="${not empty Sergey}"><%--
        --%><label for="groupModeId">Искать в группе</label><%--
       --%></jstl:if><%--
      --%></td><%--
      --%><td><%--
       --%><jstl:if test="${not empty Sergey}"><%--
        --%><select id="groupModeId" name="groupMode" class="elem" tabindex="22"><%--
         --%><logic:iterate name="inquire_psgm_1" id="mode"><%--
          --%><option value="<jstl:out value="${mode.id}"/>"<jstl:if test="${personSearchParameters.groupMode == mode.id}"> selected</jstl:if>><jstl:out value="${mode.name}"/></option><%--
         --%></logic:iterate><%--
        --%></select><%--
       --%></jstl:if><%--
      --%></td><%--
     --%></tr><%--
     --%><tr><%--
     --%><tr><%--
      --%><td colspan="6"><%--
       --%><div align="center"><%--
        --%><button type="submit" tabindex="23">Найти</button>&nbsp;<%--
        --%><button type="button" onclick="clearSearchForm(document.getElementById('searchForm'))" tabindex="24">Очистить</button><%--
       --%></div><%--
      --%></td><%--
     --%></tr><%--        
    --%></tbody><%--
   --%></table><%--
  --%></form><%--
 --%></body><%--
--%></html><%--
--%><!-- } jsps/person/search.jsp -->
