-- Generated by nsi.perl script at Sat Dec 27 17:11:24 2003

DROP TABLE call_expenses_kinds;

BEGIN;

CREATE TABLE call_expenses_kinds (
    id int4 NOT NULL PRIMARY KEY,
    name text NOT NULL UNIQUE CHECK (name <> ''),
    units text CHECK (units <> '')
);

COMMENT ON TABLE call_expenses_kinds IS 'Виды расходов по мобильному телефону';

COMMENT ON COLUMN call_expenses_kinds.id IS 'Числовое значение';
COMMENT ON COLUMN call_expenses_kinds.name IS 'Смысловое значение';
COMMENT ON COLUMN call_expenses_kinds.units IS 'Название еденицы измерения';

REVOKE ALL ON call_expenses_kinds FROM PUBLIC;
REVOKE ALL ON call_expenses_kinds FROM j2eeagent;
REVOKE ALL ON call_expenses_kinds FROM apacheagent;
GRANT SELECT, INSERT, UPDATE, DELETE ON call_expenses_kinds TO j2eeagent;
GRANT SELECT, INSERT, UPDATE, DELETE ON call_expenses_kinds TO apacheagent;

INSERT INTO call_expenses_kinds (id, name, units) VALUES (1, 'Абонентская плата', null);
INSERT INTO call_expenses_kinds (id, name, units) VALUES (2, 'Детализированный счет', null);
INSERT INTO call_expenses_kinds (id, name, units) VALUES (3, 'Определитель номера', null);
INSERT INTO call_expenses_kinds (id, name, units) VALUES (4, 'НДС', null);
INSERT INTO call_expenses_kinds (id, name, units) VALUES (5, 'Налог с продаж', null);
INSERT INTO call_expenses_kinds (id, name, units) VALUES (6, 'SMS исходящее: Би Лайн г. Москвы', 'шт');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (7, 'SMS входящее', 'шт');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (8, 'SMS исходящее', 'шт');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (9, 'Входящая связь (мин)', 'мин');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (10, 'Входящая связь (сек)', 'сек');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (11, 'Входящая связь: Би Лайн г. Москвы (мин)', 'мин');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (12, 'Входящая связь: Би Лайн г. Москвы (сек)', 'сек');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (13, 'Входящая связь: сотовые операторы г. Москвы (мин)', 'мин');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (14, 'Входящая связь: сотовые операторы г. Москвы (сек)', 'сек');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (15, 'Исходящая связь: Би Лайн г. Москвы (мин)', 'мин');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (16, 'Исходящая связь: Би Лайн г. Москвы (сек)', 'сек');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (17, 'Исходящая связь: локальная (мин)', 'мин');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (18, 'Исходящая связь: локальная (сек)', 'сек');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (19, 'Исходящая связь: мобильная Любимый номер (мин)', 'мин');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (20, 'Исходящая связь: мобильная Любимый номер (сек)', 'сек');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (21, 'Исходящая связь: мобильная (мин)', 'мин');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (22, 'Исходящая связь: мобильная (сек)', 'сек');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (23, 'Исходящая связь: справка', 'мин');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (24, 'Исходящая связь: служба спасения', 'мин');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (25, 'Входящий трафик GPRS-интернет', '40960 байт');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (26, 'Исходящий трафик GPRS-интернет', '40960 байт');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (27, 'Роуминг. Входящая связь. Россия: Кубань GSM', 'мин');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (28, 'Роуминг. Исходящая связь. Россия: Кубань GSM', 'мин');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (29, 'Роуминг. Входящая связь. Ф-л МТС: Ярославль', 'мин');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (30, 'Роуминг. Иcходящая связь. Ф-л МТС: Ярославль', 'мин');
INSERT INTO call_expenses_kinds (id, name, units) VALUES (31, 'Иcходящая связь. Международная', 'мин');

COMMIT;
