-- Generated by nsi.perl script at Sat Dec 27 17:01:15 2003

DROP TABLE call_types;

BEGIN;

CREATE TABLE call_types (
    id int4 NOT NULL PRIMARY KEY,
    name text NOT NULL UNIQUE CHECK (name <> '')
);

COMMENT ON TABLE call_types IS 'Типы звонков';

COMMENT ON COLUMN call_types.id IS 'Числовое значение';
COMMENT ON COLUMN call_types.name IS 'Смысловое значение';

REVOKE ALL ON call_types FROM PUBLIC;
REVOKE ALL ON call_types FROM j2eeagent;
REVOKE ALL ON call_types FROM apacheagent;
GRANT SELECT, INSERT, UPDATE, DELETE ON call_types TO j2eeagent;
GRANT SELECT, INSERT, UPDATE, DELETE ON call_types TO apacheagent;

INSERT INTO call_types (id, name) VALUES (1, 'Телефон');
INSERT INTO call_types (id, name) VALUES (2, 'SMS');
INSERT INTO call_types (id, name) VALUES (3, 'МЧС');

COMMIT;
