-- Generated by table.perl script at Thu Oct 30 19:57:28 2003

DROP TABLE genders;

BEGIN;

CREATE TABLE genders (
    id int4 NOT NULL
            PRIMARY KEY,
    name text CHECK (name <> '')
);

COMMENT ON TABLE genders IS 'Справочник биологических полов';

COMMENT ON COLUMN genders.id IS 'Числовое значение';
COMMENT ON COLUMN genders.name IS 'Смысловое значение';

REVOKE ALL ON genders FROM PUBLIC;
REVOKE ALL ON genders FROM j2eeagent;
REVOKE ALL ON genders FROM apacheagent;
GRANT SELECT, INSERT, UPDATE, DELETE ON genders TO j2eeagent;
GRANT SELECT, INSERT, UPDATE, DELETE ON genders TO apacheagent;

INSERT INTO genders (id, name) VALUES (0, 'Мужской');
INSERT INTO genders (id, name) VALUES (1, 'Женский');

COMMIT;
