-- Generated by nsi.perl script at Sat Dec 27 17:01:15 2003

DROP TABLE months;

BEGIN;

CREATE TABLE months (
    id int4 NOT NULL PRIMARY KEY,
    name text NOT NULL UNIQUE CHECK (name <> '')
);

COMMENT ON TABLE months IS 'Названия месяцев';

COMMENT ON COLUMN months.id IS 'Числовое значение';
COMMENT ON COLUMN months.name IS 'Смысловое значение';

REVOKE ALL ON months FROM PUBLIC;
REVOKE ALL ON months FROM j2eeagent;
REVOKE ALL ON months FROM apacheagent;
GRANT SELECT, INSERT, UPDATE, DELETE ON months TO j2eeagent;
GRANT SELECT, INSERT, UPDATE, DELETE ON months TO apacheagent;

INSERT INTO months (id, name) VALUES (1, 'Январь');
INSERT INTO months (id, name) VALUES (2, 'Февраль');
INSERT INTO months (id, name) VALUES (3, 'Март');
INSERT INTO months (id, name) VALUES (4, 'Апрель');
INSERT INTO months (id, name) VALUES (5, 'Май');
INSERT INTO months (id, name) VALUES (6, 'Июнь');
INSERT INTO months (id, name) VALUES (7, 'Июль');
INSERT INTO months (id, name) VALUES (8, 'Август');
INSERT INTO months (id, name) VALUES (9, 'Сентябрь');
INSERT INTO months (id, name) VALUES (10, 'Октябрь');
INSERT INTO months (id, name) VALUES (11, 'Ноябрь');
INSERT INTO months (id, name) VALUES (12, 'Декабрь');

COMMIT;
