-- Generated by table.perl script at Sun Dec 14 01:29:27 2003

DROP TABLE psgm;

BEGIN;

CREATE TABLE psgm (
    id int4 NOT NULL
            PRIMARY KEY,
    name text NOT NULL
              CHECK (name <> '')
);

COMMENT ON TABLE psgm IS 'Режимы поиска по группам людей';

COMMENT ON COLUMN psgm.id IS 'Числовое значение';
COMMENT ON COLUMN psgm.name IS 'Смысловое значение';

REVOKE ALL ON psgm FROM PUBLIC;
REVOKE ALL ON psgm FROM j2eeagent;
REVOKE ALL ON psgm FROM apacheagent;
GRANT SELECT, INSERT, UPDATE, DELETE ON psgm TO j2eeagent;
GRANT SELECT, INSERT, UPDATE, DELETE ON psgm TO apacheagent;

INSERT INTO psgm (id, name) VALUES (0, 'Все');
INSERT INTO psgm (id, name) VALUES (1, 'Сослуживцы');
INSERT INTO psgm (id, name) VALUES (2, 'МГУ');
INSERT INTO psgm (id, name) VALUES (3, 'ШНИП');
INSERT INTO psgm (id, name) VALUES (4, 'Родственники');
INSERT INTO psgm (id, name) VALUES (5, 'Друзья');

COMMIT;
