-- Generated by nsi.perl script at Sat Dec 27 17:01:15 2003

DROP TABLE reports;

BEGIN;

CREATE TABLE reports (
    id int4 NOT NULL PRIMARY KEY,
    name text NOT NULL UNIQUE CHECK (name <> ''),
    builder text NOT NULL CHECK (builder <> '')
);

COMMENT ON TABLE reports IS 'Виды отчетов';

COMMENT ON COLUMN reports.id IS 'Числовое значение';
COMMENT ON COLUMN reports.name IS 'Смысловое значение';
COMMENT ON COLUMN reports.builder IS 'Имя Java-класса построителя отчетов';

REVOKE ALL ON reports FROM PUBLIC;
REVOKE ALL ON reports FROM j2eeagent;
REVOKE ALL ON reports FROM apacheagent;
GRANT SELECT, INSERT, UPDATE, DELETE ON reports TO j2eeagent;
GRANT SELECT, INSERT, UPDATE, DELETE ON reports TO apacheagent;

INSERT INTO reports (id, name, builder) VALUES (1, 'Отчет о личностях', 'su.sergey.contacts.person.PersonReportBuilder');
INSERT INTO reports (id, name, builder) VALUES (2, 'Отчет об организациях', 'su.sergey.contacts.supply.SupplyReportBuilder');
INSERT INTO reports (id, name, builder) VALUES (3, 'Отчет о звонках', 'su.sergey.contacts.calls.CallReportBuilder');

COMMIT;
