package SavingsServer;


/**
* SavingsServer/HelloOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from SavingsServer.idl
* 20 Ноябрь 2005 г. 1:24:24 MSK
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
