/*
 * Generated by nsi.perl at Mon Sep 20 18:42:31 2004
 */
package su.sergey.contacts.inquiry;

/**
 * InquiryModes - Режимы получения справочных данных системы
 * Значения, определенные в этом интерфейсе описаны в таблице inquiry_modes
 */
public interface InquiryModes {
    /**
     * Коллекция
     */
    int COLLECTION = 1;

    /**
     * Отображение
     */
    int MAP = 2;
}
