package billing;


/**
* billing/_FilialFacadeStub.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from idl/interface.idl
* 25 Апрель 2004 г. 19:40:17 MSD
*/

public class _FilialFacadeStub extends org.omg.CORBA.portable.ObjectImpl implements billing.FilialFacade
{
  // Constructors
  // NOTE:  If the default constructor is used, the
  //        object is useless until _set_delegate (...)
  //        is called.
  public _FilialFacadeStub ()
  {
    super ();
  }

  public _FilialFacadeStub (org.omg.CORBA.portable.Delegate delegate)
  {
    super ();
    _set_delegate (delegate);
  }

  public void doTestIn1 (long code)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestIn1", true);
       _out.write_longlong (code);
       _in = _invoke (_out);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestIn1 (code);
    } finally {
        _releaseReply (_in);
    }
  } // doTestIn1

  public void doTestIn2 (String str)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestIn2", true);
       _out.write_string (str);
       _in = _invoke (_out);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestIn2 (str);
    } finally {
        _releaseReply (_in);
    }
  } // doTestIn2

  public void doTestIn3 (String str)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestIn3", true);
       _out.write_wstring (str);
       _in = _invoke (_out);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestIn3 (str);
    } finally {
        _releaseReply (_in);
    }
  } // doTestIn3

  public void doTestIn4 (byte[] str)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestIn4", true);
       billing.BinaryHelper.write (_out, str);
       _in = _invoke (_out);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestIn4 (str);
    } finally {
        _releaseReply (_in);
    }
  } // doTestIn4

  public void doTestIn5 (billing.Value value)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestIn5", true);
       billing.ValueHelper.write (_out, value);
       _in = _invoke (_out);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestIn5 (value);
    } finally {
        _releaseReply (_in);
    }
  } // doTestIn5

  public void doTestIn6 (billing.Value[] values)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestIn6", true);
       billing.ValuesHelper.write (_out, values);
       _in = _invoke (_out);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestIn6 (values);
    } finally {
        _releaseReply (_in);
    }
  } // doTestIn6

  public void doTestIn7 (billing.ComplexValue value)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestIn7", true);
       billing.ComplexValueHelper.write (_out, value);
       _in = _invoke (_out);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestIn7 (value);
    } finally {
        _releaseReply (_in);
    }
  } // doTestIn7

  public void doTestIn8 (billing.ComplexValue[] values)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestIn8", true);
       billing.ComplexValuesHelper.write (_out, values);
       _in = _invoke (_out);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestIn8 (values);
    } finally {
        _releaseReply (_in);
    }
  } // doTestIn8

  public void doTestOut1 (org.omg.CORBA.LongHolder code)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestOut1", true);
       _in = _invoke (_out);
       code.value = _in.read_longlong ();
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestOut1 (code);
    } finally {
        _releaseReply (_in);
    }
  } // doTestOut1

  public void doTestOut2 (org.omg.CORBA.StringHolder str)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestOut2", true);
       _in = _invoke (_out);
       str.value = _in.read_string ();
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestOut2 (str);
    } finally {
        _releaseReply (_in);
    }
  } // doTestOut2

  public void doTestOut3 (org.omg.CORBA.StringHolder str)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestOut3", true);
       _in = _invoke (_out);
       str.value = _in.read_wstring ();
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestOut3 (str);
    } finally {
        _releaseReply (_in);
    }
  } // doTestOut3

  public void doTestOut4 (billing.BinaryHolder str)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestOut4", true);
       _in = _invoke (_out);
       str.value = billing.BinaryHelper.read (_in);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestOut4 (str);
    } finally {
        _releaseReply (_in);
    }
  } // doTestOut4

  public void doTestOut5 (billing.ValueHolder value)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestOut5", true);
       _in = _invoke (_out);
       value.value = billing.ValueHelper.read (_in);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestOut5 (value);
    } finally {
        _releaseReply (_in);
    }
  } // doTestOut5

  public void doTestOut6 (billing.ValuesHolder values)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestOut6", true);
       _in = _invoke (_out);
       values.value = billing.ValuesHelper.read (_in);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestOut6 (values);
    } finally {
        _releaseReply (_in);
    }
  } // doTestOut6

  public void doTestOut7 (billing.ComplexValueHolder value)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestOut7", true);
       _in = _invoke (_out);
       value.value = billing.ComplexValueHelper.read (_in);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestOut7 (value);
    } finally {
        _releaseReply (_in);
    }
  } // doTestOut7

  public void doTestOut8 (billing.ComplexValuesHolder value)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestOut8", true);
       _in = _invoke (_out);
       value.value = billing.ComplexValuesHelper.read (_in);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doTestOut8 (value);
    } finally {
        _releaseReply (_in);
    }
  } // doTestOut8

  public long doTestResult1 ()
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestResult1", true);
       _in = _invoke (_out);
       long __result = _in.read_longlong ();
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return doTestResult1 ();
    } finally {
        _releaseReply (_in);
    }
  } // doTestResult1

  public String doTestResult2 ()
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestResult2", true);
       _in = _invoke (_out);
       String __result = _in.read_string ();
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return doTestResult2 ();
    } finally {
        _releaseReply (_in);
    }
  } // doTestResult2

  public String doTestResult3 ()
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestResult3", true);
       _in = _invoke (_out);
       String __result = _in.read_wstring ();
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return doTestResult3 ();
    } finally {
        _releaseReply (_in);
    }
  } // doTestResult3

  public byte[] doTestResult4 ()
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestResult4", true);
       _in = _invoke (_out);
       byte __result[] = billing.BinaryHelper.read (_in);
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return doTestResult4 ();
    } finally {
        _releaseReply (_in);
    }
  } // doTestResult4

  public billing.Value doTestResult5 ()
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestResult5", true);
       _in = _invoke (_out);
       billing.Value __result = billing.ValueHelper.read (_in);
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return doTestResult5 ();
    } finally {
        _releaseReply (_in);
    }
  } // doTestResult5

  public billing.Value[] doTestResult6 ()
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestResult6", true);
       _in = _invoke (_out);
       billing.Value __result[] = billing.ValuesHelper.read (_in);
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return doTestResult6 ();
    } finally {
        _releaseReply (_in);
    }
  } // doTestResult6

  public billing.ComplexValue doTestResult7 ()
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestResult7", true);
       _in = _invoke (_out);
       billing.ComplexValue __result = billing.ComplexValueHelper.read (_in);
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return doTestResult7 ();
    } finally {
        _releaseReply (_in);
    }
  } // doTestResult7

  public billing.ComplexValue[] doTestResult8 ()
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doTestResult8", true);
       _in = _invoke (_out);
       billing.ComplexValue __result[] = billing.ComplexValuesHelper.read (_in);
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return doTestResult8 ();
    } finally {
        _releaseReply (_in);
    }
  } // doTestResult8

  public void doExtraTestIn1 (billing.ExtraComplexValue value)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doExtraTestIn1", true);
       billing.ExtraComplexValueHelper.write (_out, value);
       _in = _invoke (_out);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doExtraTestIn1 (value);
    } finally {
        _releaseReply (_in);
    }
  } // doExtraTestIn1

  public void doExtraTestIn2 (billing.ExtraComplexValue[] values)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doExtraTestIn2", true);
       billing.ExtraComplexValuesHelper.write (_out, values);
       _in = _invoke (_out);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doExtraTestIn2 (values);
    } finally {
        _releaseReply (_in);
    }
  } // doExtraTestIn2

  public void doExtraTestOut1 (billing.ExtraComplexValueHolder value)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doExtraTestOut1", true);
       _in = _invoke (_out);
       value.value = billing.ExtraComplexValueHelper.read (_in);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doExtraTestOut1 (value);
    } finally {
        _releaseReply (_in);
    }
  } // doExtraTestOut1

  public void doExtraTestOut2 (billing.ExtraComplexValuesHolder values)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doExtraTestOut2", true);
       _in = _invoke (_out);
       values.value = billing.ExtraComplexValuesHelper.read (_in);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       doExtraTestOut2 (values);
    } finally {
        _releaseReply (_in);
    }
  } // doExtraTestOut2

  public billing.ExtraComplexValue doExtraTestResult1 ()
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doExtraTestResult1", true);
       _in = _invoke (_out);
       billing.ExtraComplexValue __result = billing.ExtraComplexValueHelper.read (_in);
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return doExtraTestResult1 ();
    } finally {
        _releaseReply (_in);
    }
  } // doExtraTestResult1

  public billing.ExtraComplexValue[] doExtraTestResult2 ()
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("doExtraTestResult2", true);
       _in = _invoke (_out);
       billing.ExtraComplexValue __result[] = billing.ExtraComplexValuesHelper.read (_in);
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return doExtraTestResult2 ();
    } finally {
        _releaseReply (_in);
    }
  } // doExtraTestResult2

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:billing/FilialFacade:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s)
  {
     try 
     {
       String str = s.readUTF ();
       org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init ().string_to_object (str);
       org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
       _set_delegate (delegate);
     } catch (java.io.IOException e) {}
  }

  private void writeObject (java.io.ObjectOutputStream s)
  {
     try 
     {
       String str = org.omg.CORBA.ORB.init ().object_to_string (this);
       s.writeUTF (str);
     } catch (java.io.IOException e) {}
  }
} // class _FilialFacadeStub
