package billing;


/**
* billing/ExtraComplexValue.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from idl/interface.idl
* 25 Апрель 2004 г. 19:40:17 MSD
*/

public final class ExtraComplexValue implements org.omg.CORBA.portable.IDLEntity
{
  public long code = (long)0;
  public byte message[] = null;
  public billing.ComplexValue values[] = null;

  public ExtraComplexValue ()
  {
  } // ctor

  public ExtraComplexValue (long _code, byte[] _message, billing.ComplexValue[] _values)
  {
    code = _code;
    message = _message;
    values = _values;
  } // ctor

} // class ExtraComplexValue
