package billing;

/**
* billing/ExtraComplexValueHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from idl/interface.idl
* 25 Апрель 2004 г. 19:40:17 MSD
*/

public final class ExtraComplexValueHolder implements org.omg.CORBA.portable.Streamable
{
  public billing.ExtraComplexValue value = null;

  public ExtraComplexValueHolder ()
  {
  }

  public ExtraComplexValueHolder (billing.ExtraComplexValue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = billing.ExtraComplexValueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    billing.ExtraComplexValueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return billing.ExtraComplexValueHelper.type ();
  }

}
