package billing;

/**
* billing/FilialFacadeHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from idl/interface.idl
* 25 Апрель 2004 г. 19:40:17 MSD
*/

public final class FilialFacadeHolder implements org.omg.CORBA.portable.Streamable
{
  public billing.FilialFacade value = null;

  public FilialFacadeHolder ()
  {
  }

  public FilialFacadeHolder (billing.FilialFacade initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = billing.FilialFacadeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    billing.FilialFacadeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return billing.FilialFacadeHelper.type ();
  }

}
