package billing;


/**
* billing/FilialFacade.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from idl/interface.idl
* 25 Апрель 2004 г. 19:40:17 MSD
*/

public interface FilialFacade extends FilialFacadeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FilialFacade
