package billing;


/**
* billing/_FilialFacadeImplBase.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from idl/interface.idl
* 25 Апрель 2004 г. 19:39:23 MSD
*/

public abstract class _FilialFacadeImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements billing.FilialFacade, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _FilialFacadeImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("doTestIn1", new java.lang.Integer (0));
    _methods.put ("doTestIn2", new java.lang.Integer (1));
    _methods.put ("doTestIn3", new java.lang.Integer (2));
    _methods.put ("doTestIn4", new java.lang.Integer (3));
    _methods.put ("doTestIn5", new java.lang.Integer (4));
    _methods.put ("doTestIn6", new java.lang.Integer (5));
    _methods.put ("doTestIn7", new java.lang.Integer (6));
    _methods.put ("doTestIn8", new java.lang.Integer (7));
    _methods.put ("doTestOut1", new java.lang.Integer (8));
    _methods.put ("doTestOut2", new java.lang.Integer (9));
    _methods.put ("doTestOut3", new java.lang.Integer (10));
    _methods.put ("doTestOut4", new java.lang.Integer (11));
    _methods.put ("doTestOut5", new java.lang.Integer (12));
    _methods.put ("doTestOut6", new java.lang.Integer (13));
    _methods.put ("doTestOut7", new java.lang.Integer (14));
    _methods.put ("doTestOut8", new java.lang.Integer (15));
    _methods.put ("doTestResult1", new java.lang.Integer (16));
    _methods.put ("doTestResult2", new java.lang.Integer (17));
    _methods.put ("doTestResult3", new java.lang.Integer (18));
    _methods.put ("doTestResult4", new java.lang.Integer (19));
    _methods.put ("doTestResult5", new java.lang.Integer (20));
    _methods.put ("doTestResult6", new java.lang.Integer (21));
    _methods.put ("doTestResult7", new java.lang.Integer (22));
    _methods.put ("doTestResult8", new java.lang.Integer (23));
    _methods.put ("doExtraTestIn1", new java.lang.Integer (24));
    _methods.put ("doExtraTestIn2", new java.lang.Integer (25));
    _methods.put ("doExtraTestOut1", new java.lang.Integer (26));
    _methods.put ("doExtraTestOut2", new java.lang.Integer (27));
    _methods.put ("doExtraTestResult1", new java.lang.Integer (28));
    _methods.put ("doExtraTestResult2", new java.lang.Integer (29));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get (method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // billing/FilialFacade/doTestIn1
       {
         long code = in.read_longlong ();
         this.doTestIn1 (code);
         out = rh.createReply();
         break;
       }

       case 1:  // billing/FilialFacade/doTestIn2
       {
         String str = in.read_string ();
         this.doTestIn2 (str);
         out = rh.createReply();
         break;
       }

       case 2:  // billing/FilialFacade/doTestIn3
       {
         String str = in.read_wstring ();
         this.doTestIn3 (str);
         out = rh.createReply();
         break;
       }

       case 3:  // billing/FilialFacade/doTestIn4
       {
         byte str[] = billing.BinaryHelper.read (in);
         this.doTestIn4 (str);
         out = rh.createReply();
         break;
       }

       case 4:  // billing/FilialFacade/doTestIn5
       {
         billing.Value value = billing.ValueHelper.read (in);
         this.doTestIn5 (value);
         out = rh.createReply();
         break;
       }

       case 5:  // billing/FilialFacade/doTestIn6
       {
         billing.Value values[] = billing.ValuesHelper.read (in);
         this.doTestIn6 (values);
         out = rh.createReply();
         break;
       }

       case 6:  // billing/FilialFacade/doTestIn7
       {
         billing.ComplexValue value = billing.ComplexValueHelper.read (in);
         this.doTestIn7 (value);
         out = rh.createReply();
         break;
       }

       case 7:  // billing/FilialFacade/doTestIn8
       {
         billing.ComplexValue values[] = billing.ComplexValuesHelper.read (in);
         this.doTestIn8 (values);
         out = rh.createReply();
         break;
       }

       case 8:  // billing/FilialFacade/doTestOut1
       {
         org.omg.CORBA.LongHolder code = new org.omg.CORBA.LongHolder ();
         this.doTestOut1 (code);
         out = rh.createReply();
         out.write_longlong (code.value);
         break;
       }

       case 9:  // billing/FilialFacade/doTestOut2
       {
         org.omg.CORBA.StringHolder str = new org.omg.CORBA.StringHolder ();
         this.doTestOut2 (str);
         out = rh.createReply();
         out.write_string (str.value);
         break;
       }

       case 10:  // billing/FilialFacade/doTestOut3
       {
         org.omg.CORBA.StringHolder str = new org.omg.CORBA.StringHolder ();
         this.doTestOut3 (str);
         out = rh.createReply();
         out.write_wstring (str.value);
         break;
       }

       case 11:  // billing/FilialFacade/doTestOut4
       {
         billing.BinaryHolder str = new billing.BinaryHolder ();
         this.doTestOut4 (str);
         out = rh.createReply();
         billing.BinaryHelper.write (out, str.value);
         break;
       }

       case 12:  // billing/FilialFacade/doTestOut5
       {
         billing.ValueHolder value = new billing.ValueHolder ();
         this.doTestOut5 (value);
         out = rh.createReply();
         billing.ValueHelper.write (out, value.value);
         break;
       }

       case 13:  // billing/FilialFacade/doTestOut6
       {
         billing.ValuesHolder values = new billing.ValuesHolder ();
         this.doTestOut6 (values);
         out = rh.createReply();
         billing.ValuesHelper.write (out, values.value);
         break;
       }

       case 14:  // billing/FilialFacade/doTestOut7
       {
         billing.ComplexValueHolder value = new billing.ComplexValueHolder ();
         this.doTestOut7 (value);
         out = rh.createReply();
         billing.ComplexValueHelper.write (out, value.value);
         break;
       }

       case 15:  // billing/FilialFacade/doTestOut8
       {
         billing.ComplexValuesHolder value = new billing.ComplexValuesHolder ();
         this.doTestOut8 (value);
         out = rh.createReply();
         billing.ComplexValuesHelper.write (out, value.value);
         break;
       }

       case 16:  // billing/FilialFacade/doTestResult1
       {
         long __result = (long)0;
         __result = this.doTestResult1 ();
         out = rh.createReply();
         out.write_longlong (__result);
         break;
       }

       case 17:  // billing/FilialFacade/doTestResult2
       {
         String __result = null;
         __result = this.doTestResult2 ();
         out = rh.createReply();
         out.write_string (__result);
         break;
       }

       case 18:  // billing/FilialFacade/doTestResult3
       {
         String __result = null;
         __result = this.doTestResult3 ();
         out = rh.createReply();
         out.write_wstring (__result);
         break;
       }

       case 19:  // billing/FilialFacade/doTestResult4
       {
         byte __result[] = null;
         __result = this.doTestResult4 ();
         out = rh.createReply();
         billing.BinaryHelper.write (out, __result);
         break;
       }

       case 20:  // billing/FilialFacade/doTestResult5
       {
         billing.Value __result = null;
         __result = this.doTestResult5 ();
         out = rh.createReply();
         billing.ValueHelper.write (out, __result);
         break;
       }

       case 21:  // billing/FilialFacade/doTestResult6
       {
         billing.Value __result[] = null;
         __result = this.doTestResult6 ();
         out = rh.createReply();
         billing.ValuesHelper.write (out, __result);
         break;
       }

       case 22:  // billing/FilialFacade/doTestResult7
       {
         billing.ComplexValue __result = null;
         __result = this.doTestResult7 ();
         out = rh.createReply();
         billing.ComplexValueHelper.write (out, __result);
         break;
       }

       case 23:  // billing/FilialFacade/doTestResult8
       {
         billing.ComplexValue __result[] = null;
         __result = this.doTestResult8 ();
         out = rh.createReply();
         billing.ComplexValuesHelper.write (out, __result);
         break;
       }

       case 24:  // billing/FilialFacade/doExtraTestIn1
       {
         billing.ExtraComplexValue value = billing.ExtraComplexValueHelper.read (in);
         this.doExtraTestIn1 (value);
         out = rh.createReply();
         break;
       }

       case 25:  // billing/FilialFacade/doExtraTestIn2
       {
         billing.ExtraComplexValue values[] = billing.ExtraComplexValuesHelper.read (in);
         this.doExtraTestIn2 (values);
         out = rh.createReply();
         break;
       }

       case 26:  // billing/FilialFacade/doExtraTestOut1
       {
         billing.ExtraComplexValueHolder value = new billing.ExtraComplexValueHolder ();
         this.doExtraTestOut1 (value);
         out = rh.createReply();
         billing.ExtraComplexValueHelper.write (out, value.value);
         break;
       }

       case 27:  // billing/FilialFacade/doExtraTestOut2
       {
         billing.ExtraComplexValuesHolder values = new billing.ExtraComplexValuesHolder ();
         this.doExtraTestOut2 (values);
         out = rh.createReply();
         billing.ExtraComplexValuesHelper.write (out, values.value);
         break;
       }

       case 28:  // billing/FilialFacade/doExtraTestResult1
       {
         billing.ExtraComplexValue __result = null;
         __result = this.doExtraTestResult1 ();
         out = rh.createReply();
         billing.ExtraComplexValueHelper.write (out, __result);
         break;
       }

       case 29:  // billing/FilialFacade/doExtraTestResult2
       {
         billing.ExtraComplexValue __result[] = null;
         __result = this.doExtraTestResult2 ();
         out = rh.createReply();
         billing.ExtraComplexValuesHelper.write (out, __result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:billing/FilialFacade:1.0"};

  public String[] _ids ()
  {
    return __ids;
  }


} // class _FilialFacadeImplBase
