package billing;


/**
* billing/BinaryHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from idl/interface.idl
* 25 Апрель 2004 г. 19:39:23 MSD
*/

public final class BinaryHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public BinaryHolder ()
  {
  }

  public BinaryHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = billing.BinaryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    billing.BinaryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return billing.BinaryHelper.type ();
  }

}
