package billing;


/**
* billing/ComplexValuesHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from idl/interface.idl
* 25 Апрель 2004 г. 19:39:23 MSD
*/

public final class ComplexValuesHolder implements org.omg.CORBA.portable.Streamable
{
  public billing.ComplexValue value[] = null;

  public ComplexValuesHolder ()
  {
  }

  public ComplexValuesHolder (billing.ComplexValue[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = billing.ComplexValuesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    billing.ComplexValuesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return billing.ComplexValuesHelper.type ();
  }

}
