package billing;

/**
* billing/ComplexValueHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from idl/interface.idl
* 25 Апрель 2004 г. 19:39:23 MSD
*/

public final class ComplexValueHolder implements org.omg.CORBA.portable.Streamable
{
  public billing.ComplexValue value = null;

  public ComplexValueHolder ()
  {
  }

  public ComplexValueHolder (billing.ComplexValue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = billing.ComplexValueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    billing.ComplexValueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return billing.ComplexValueHelper.type ();
  }

}
