package billing;


/**
* billing/ValuesHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from idl/interface.idl
* 25 Апрель 2004 г. 19:39:23 MSD
*/

public final class ValuesHolder implements org.omg.CORBA.portable.Streamable
{
  public billing.Value value[] = null;

  public ValuesHolder ()
  {
  }

  public ValuesHolder (billing.Value[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = billing.ValuesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    billing.ValuesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return billing.ValuesHelper.type ();
  }

}
