/*
 * Generated by nsi.perl at Sat Dec 27 17:01:15 2003
 */
package su.sergey.contacts.valueobjects;

/**
 * CallTypes - Типы звонков
 * Значения, определенные в этом интерфейсе описаны в таблице call_types
 */
public interface CallTypes {
    /**
     * Телефон
     */
    Integer PHONE = new Integer(1);

    /**
     * SMS
     */
    Integer SMS = new Integer(2);

    /**
     * МЧС
     */
    Integer SOS = new Integer(3);
}
