/*
 * Generated by ./nsi.perl at Sun Dec 14 01:29:27 2003
 */
package su.sergey.contacts.valueobjects;

/**
 * Genders - Справочник биологических полов
 * Значения, определенные в этом интерфейсе описаны в таблице genders
 */
public interface Genders {
    /**
     * Мужской
     */
    Integer MALE = new Integer(0);

    /**
     * Женский
     */
    Integer FEMALE = new Integer(1);
}
