/*
 * Generated by nsi.perl at Sat Dec 27 17:01:15 2003
 */
package su.sergey.contacts.valueobjects;

/**
 * Genders - Справочник биологических полов
 * Значения, определенные в этом интерфейсе описаны в таблице genders
 */
public interface Genders {
    /**
     * Мужской
     */
    Integer MALE = new Integer(0);

    /**
     * Женский
     */
    Integer FEMALE = new Integer(1);
}
