/*
 * Generated by ./nsi.perl at Thu Oct 30 20:22:07 2003
 */
package su.sergey.contacts.valueobjects;

/**
 * Months - Названия месяцев
 * Значения, определенные в этом интерфейсе описаны в таблице months
 */
public interface Months {
    /**
     * Январь
     */
    Integer JANUARY = new Integer(1);

    /**
     * Февраль
     */
    Integer FEBRUARY = new Integer(2);

    /**
     * Март
     */
    Integer MARCH = new Integer(3);

    /**
     * Апрель
     */
    Integer APRIL = new Integer(4);

    /**
     * Май
     */
    Integer MAY = new Integer(5);

    /**
     * Июнь
     */
    Integer JUNE = new Integer(6);

    /**
     * Июль
     */
    Integer JULY = new Integer(7);

    /**
     * Август
     */
    Integer AUGUST = new Integer(8);

    /**
     * Сентябрь
     */
    Integer SEPTEMBER = new Integer(9);

    /**
     * Октябрь
     */
    Integer OCTOBER = new Integer(10);

    /**
     * Ноябрь
     */
    Integer NOVEMBER = new Integer(11);

    /**
     * Декабрь
     */
    Integer DECEMBER = new Integer(12);
}
