/*
 * Generated by ./nsi.perl at Sun Dec 14 01:29:27 2003
 */
package su.sergey.contacts.valueobjects;

/**
 * PersonSearchGroupModes - Режимы поиска по группам людей
 * Значения, определенные в этом интерфейсе описаны в таблице psgm
 */
public interface PersonSearchGroupModes {
    /**
     * Все
     */
    Integer ANY = new Integer(0);

    /**
     * Сослуживцы
     */
    Integer COWORKER = new Integer(1);

    /**
     * МГУ
     */
    Integer MSU = new Integer(2);

    /**
     * ШНИП
     */
    Integer SHNIP = new Integer(3);

    /**
     * Родственники
     */
    Integer RELATED = new Integer(4);

    /**
     * Друзья
     */
    Integer FRIEND = new Integer(5);
}
