/*
 * Generated by nsi.perl at Sat Dec 27 17:01:15 2003
 */
package su.sergey.contacts.valueobjects;

/**
 * Reports - Виды отчетов
 * Значения, определенные в этом интерфейсе описаны в таблице reports
 */
public interface Reports {
    /**
     * Отчет о личностях
     */
    Integer PERSONS = new Integer(1);

    /**
     * Отчет об организациях
     */
    Integer SUPPLIES = new Integer(2);

    /**
     * Отчет о звонках
     */
    Integer CALLS = new Integer(3);
}
