/*
 * Generated by ./nsi.perl at Sun Dec 14 01:29:27 2003
 */
package su.sergey.contacts.valueobjects;

/**
 * Reports - Виды отчетов
 * Значения, определенные в этом интерфейсе описаны в таблице reports
 */
public interface Reports {
    /**
     * Отчет о личностях
     */
    Integer PERSONS = new Integer(1);

    /**
     * Отчет об организациях
     */
    Integer SUPPLIES = new Integer(2);

    /**
     * Отчет о звонках
     */
    Integer CALLS = new Integer(3);
}
