#! /bin/bash

if [ -z "$WAS_HOME" ]; then
    echo "WAS_HOME environment variable not provided" >&2
    exit 1
fi

if [ "$#" != "2" ]; then
    echo "Usage: install-ear <ear-file> <enterprise-app>" >&2
    exit 1
fi

ear="$1"
application="$2"

flags=""
if [ "$PRECOMPILE_JSP" = "true" ]; then
    flags="$flags -preCompileJSPs"
fi

if [ "$EJB_DEPLOY" = "true" ]; then
    flags="$flags -deployejb"
fi

if "$WAS_HOME/bin/wsadmin.sh" -conntype NONE -c '$AdminApp list' | grep -q "$application"; then
    flags="$flags -update -appname $application"
fi
"$WAS_HOME/bin/wsadmin.sh" -conntype NONE -c '$AdminApp install '"$ear"' "'"$flags"'"; $AdminConfig save' || exit $?
