#! /bin/sh
# chkconfig: - 90 10
# description: Starts and stops the WebSphere Application Server
# pidfile: /var/run/websphere5.pid
# config: /usr/local/websphere5/config/server-cfg.xml
#
# The function action from /etc/rc.d/init.d/functions is not used.
#

WAS_HOME="/usr/local/websphere5"
pidfile="/var/run/websphere5.pid"
lockfile="/var/lock/subsys/websphere5"
server="server1"
username="wasadmin"
password="changeitxxx"

[ -x "$WAS_HOME/bin/startServer.sh" ] || exit 0
[ -x "$WAS_HOME/bin/stopServer.sh" ] || exit 0

. /etc/rc.d/init.d/functions

export LC_CTYPE LC_MONETARY LANGUAGE LC_TIME LC_NUMERIC LC_COLLATE LC_MESSAGES LANG

# See how we were called.
case "$1" in
    start)
	pid=""
	if [ -f "$pidfile" ]; then
	    pid="$(cat "$pidfile")"
	    ps "$pid" >/dev/null || pid=""
	fi
	if [ -n "$pid" ]; then
	    echo -n "Starting websphere5: (already running) check $pidfile"
	    echo_failure
	    echo
	else
            echo -n "Starting websphere5: "
	    pid="$("$WAS_HOME/bin/startServer.sh" "$server" -nowait |  awk '/^ADMU3000I:/ {a = 0 + $NF; print a;}')"
            if [ -n "$pid" -a "$pid" != "-1" ]; then
		echo -n "websphere5 [$pid]"
		echo_success
		echo
	        echo "$pid" > "$pidfile"
		echo > "$lockfile"
	    else
		echo_failure
		echo
	    fi
	fi
	;;
    stop)
	pid=""
        if [ -f "$pidfile" ]; then
	    pid="$(cat "$pidfile")"
            echo -n "Stopping websphere5: "
	    if "$WAS_HOME/bin/stopServer.sh" "$server" -username "$username" -password "$password" >/dev/null; then
                rm -f "$pidfile"
	        rm -f "$lockfile"
		echo_success
		echo
	    else
	        echo_failure
		echo
	    fi
	else
	    echo -n "Stopping websphere5: not running"
            echo_success
            echo
	fi
	;;
    status)
        pid=""
        if [ -f "$pidfile" ]; then
	    pid="$(cat "$pidfile")"
	    ps "$pid" >/dev/null || pid=""
	fi
	if [ -n "$pid" ]; then
	    echo "websphere5 (pid $pid) is running..."
	else
	    echo "websphere5 is stopped"
	fi
	;;
    restart)
	"$0" stop
	"$0" start
	;;
    *)
	echo "Usage: websphere5 {start|stop|status|restart}"
	exit 1
esac

exit 0
