#! /bin/sh
# chkconfig: - 90 10
# description: Starts and stops the WebSphere Application Server
# pidfile: /var/run/websphere.pid
# config: /usr/local/websphere/config/server-cfg.xml
#
# The function action from /etc/rc.d/init.d/functions is not used.
#

WAS_HOME="/usr/local/websphere"
SERVER_HOME="/home/system/wasadmin"
pidfile="/var/run/websphere.pid"
lockfile="/var/lock/subsys/websphere"
log_stdout="$SERVER_HOME/logs/websphere-startup-stdout.log"
log_stderr="$SERVER_HOME/logs/websphere-startup-stderr.log"

[ -x "$WAS_HOME/bin/startServer.sh" ] || exit 0
[ -x "$WAS_HOME/bin/stopServer.sh" ] || exit 0

. /etc/rc.d/init.d/functions

export LC_CTYPE LC_MONETARY LANGUAGE LC_TIME LC_NUMERIC LC_COLLATE LC_MESSAGES LANG

# See how we were called.
case "$1" in
    start)
	pid=""
	if [ -f "$pidfile" ]; then
	    pid="$(cat "$pidfile")"
	fi
	if [ -n "$pid" ]; then
	    echo -n "Starting websphere: check $pidfile"
	    echo_failure
	    echo
	else
            echo -n "Starting websphere: "
	    pid="$("$WAS_HOME/bin/startServer.sh" -noWait |  awk '/^WSPL0065I/ {a = 0 + $NF; print a;}')"
            if [ -n "$pid" -a "$pid" -ne "-1" ]; then
		echo -n "websphere [$pid]"
		echo_success
		echo
	        echo "$pid" > "$pidfile"
		echo > "$lockfile"
	    else
		echo_failure
		echo
	    fi
	fi
	;;
    stop)
        if [ -f "$pidfile" ]; then
            echo -n "Stopping websphere: "
	    umask 007
            "$WAS_HOME/bin/stopServer.sh" 1>> "$log_stdout" 2>> "$log_stderr"
	    umask 077
	    rm -f "$pidfile"
	    rm -f "$lockfile"
	else
	    echo -n "Stopping websphere: not running"
	fi
	echo_success
	echo
	;;
    status)
        pid=""
        if [ -f "$pidfile" ]; then
	    pid="$(cat "$pidfile")"
	    ps "$pid" >/dev/null || pid=""
	fi
	if [ -n "$pid" ]; then
	    echo "websphere (pid $pid) is running..."
	else
	    echo "websphere is stopped"
	fi
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: websphere {start|stop|status|restart}"
	exit 1
esac

exit 0
